import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Dashboard from "@/components/Dashboard";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Providers } from '../providers'
import { Provider } from 'react-redux';
import { store } from '../redux/store';
import React from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// RootLayout.tsx
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      {/* <Provider store={store}> */}
        <body className={inter.className}>
          <Providers>
            <AppRouterCacheProvider>
              <div className="flex">
                <div className="w-[20%]">
                  <Dashboard />
                </div>
                <div className="w-[80%] max-h-screen overflow-auto">
                  {children}
                </div>
              </div>
            </AppRouterCacheProvider>
          </Providers>
        </body>
      {/* </Provider> */}
    </html>
  );
}


